# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad_fun_cpp <- function(nlm_par, dset, lambda_theta, lambda_in, lambda_out, lambda_delta, est_par, fix_par, est_length, fix_length, fix_value, groups_map, mt_vek, mt_idx, dim_resp, all_cat, n_th, XN, XNA, eps, is_penalized_gamma, is_penalized_theta, is_penalized_delta) {
    .Call('_autoRasch_grad_fun_cpp', PACKAGE = 'autoRasch', nlm_par, dset, lambda_theta, lambda_in, lambda_out, lambda_delta, est_par, fix_par, est_length, fix_length, fix_value, groups_map, mt_vek, mt_idx, dim_resp, all_cat, n_th, XN, XNA, eps, is_penalized_gamma, is_penalized_theta, is_penalized_delta)
}

ll_cpp <- function(theta, gamma, delta, groups, beta, m_cat, X, gamma_penalized, delta_penalized, theta_penalized, lambda_in, lambda_out, lambda_delta, lambda_theta, eps) {
    .Call('_autoRasch_ll_cpp', PACKAGE = 'autoRasch', theta, gamma, delta, groups, beta, m_cat, X, gamma_penalized, delta_penalized, theta_penalized, lambda_in, lambda_out, lambda_delta, lambda_theta, eps)
}

grad_cpp <- function(theta, gamma, delta, groups, beta, m_cat, X, gamma_penalized, delta_penalized, theta_penalized, lambda_in, lambda_out, lambda_delta, lambda_theta, eps) {
    .Call('_autoRasch_grad_cpp', PACKAGE = 'autoRasch', theta, gamma, delta, groups, beta, m_cat, X, gamma_penalized, delta_penalized, theta_penalized, lambda_in, lambda_out, lambda_delta, lambda_theta, eps)
}

